id: TestCommonPython
version: -1
name: TestCommonPython
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 285c4985-7b73-4658-87b7-fa862dbe56ae
    type: start
    task:
      id: 285c4985-7b73-4658-87b7-fa862dbe56ae
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "4"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: e64dc858-7ff8-4489-86df-82045244082e
    type: regular
    task:
      id: e64dc858-7ff8-4489-86df-82045244082e
      version: -1
      name: Test DQ
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "3"
    scriptarguments:
      test_type:
        simple: DQ
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 370
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: f417598c-1fc1-4bce-81ff-334dbf652e53
    type: regular
    task:
      id: f417598c-1fc1-4bce-81ff-334dbf652e53
      version: -1
      name: Test MarkDown
      description: Tests for common functions createEntry and TableToMarkDown
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "6"
    scriptarguments:
      test_type:
        simple: MD
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 545
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: e53e595b-eeee-479d-8561-e02fead28e16
    type: regular
    task:
      id: e53e595b-eeee-479d-8561-e02fead28e16
      version: -1
      name: Test XML JSON relations
      description: 'Tests for common functions xml2json and json2xml '
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      test_type:
        simple: XML
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 195
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 618d2770-fb42-4baf-8cd3-c48a22f55d29
    type: regular
    task:
      id: 618d2770-fb42-4baf-8cd3-c48a22f55d29
      version: -1
      name: Test tableToMarkdown
      description: Tests underscoreToCamelCase and tableToMarkDown with and without
        headerTransform
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      extend-context: {}
      test_type:
        simple: TBLMD
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1070
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: 38576e49-c6b8-4b00-8b09-b8567b96e5d9
    type: regular
    task:
      id: 38576e49-c6b8-4b00-8b09-b8567b96e5d9
      version: -1
      name: Test hash function
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "14"
    scriptarguments:
      test_type:
        simple: HASH
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 999d9a18-09e9-48fb-8b33-5bfd4f75d0c6
    type: regular
    task:
      id: 999d9a18-09e9-48fb-8b33-5bfd4f75d0c6
      version: -1
      name: Test date_to_timestamp
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "10"
    scriptarguments:
      test_type:
        simple: DATE_TO_TIMESTAMP
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1420
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: 592c1bfb-4c8a-44b4-8d18-74fc7312f46b
    type: regular
    task:
      id: 592c1bfb-4c8a-44b4-8d18-74fc7312f46b
      version: -1
      name: Test camelize
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "8"
    scriptarguments:
      test_type:
        simple: CAMELIZE
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1245
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "10":
    id: "10"
    taskid: fb93cb39-b0a0-431a-8b64-11182f5a757c
    type: regular
    task:
      id: fb93cb39-b0a0-431a-8b64-11182f5a757c
      version: -1
      name: Test PascalToSpace
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "11"
    scriptarguments:
      test_type:
        simple: PASCAL_TO_SPACE
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1595
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "11":
    id: "11"
    taskid: d22911cd-e795-444f-8155-3de7e34b743b
    type: regular
    task:
      id: d22911cd-e795-444f-8155-3de7e34b743b
      version: -1
      name: Test return_outputs
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "12"
    scriptarguments:
      test_type:
        simple: RETURN_OUTPUTS
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1770
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "12":
    id: "12"
    taskid: 316ca523-6359-4586-8f03-fe71abff5c49
    type: condition
    task:
      id: 316ca523-6359-4586-8f03-fe71abff5c49
      version: -1
      name: check if context contain foo
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "13"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: foo
            iscontext: true
          right:
            value:
              simple: foo1
    view: |-
      {
        "position": {
          "x": 50,
          "y": 1945
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "13":
    id: "13"
    taskid: 5e41ecb0-1e08-4898-82ad-e3cab2e97253
    type: title
    task:
      id: 5e41ecb0-1e08-4898-82ad-e3cab2e97253
      version: -1
      name: Test Success
      type: title
      iscommand: false
      brand: ""
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 2120
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "14":
    id: "14"
    taskid: a8b15a99-3db1-4e62-8d02-3cff5faede55
    type: regular
    task:
      id: a8b15a99-3db1-4e62-8d02-3cff5faede55
      version: -1
      name: Test remove nulls from dictionary function
      scriptName: TestPYCommonServer
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "5"
    scriptarguments:
      test_type:
        simple: REMOVE_DICTIONARY_NULLS
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 50,
          "y": 895
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2135,
        "width": 380,
        "x": 50,
        "y": 50
      }
    }
  }
inputs: []
outputs: []